### ISSUE TITLE
release 1.3.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RotamerConvolveMD#18]
@katrinr added many new features and we should create a new releases.

Is there anything else that needs to be considered? @MDAnalysis/rotamerconvolvemd ?

updated todo list
- [x] docs #1 
- [x] works with recent MDAnalysis #20 
- [x] finalize update of rotamer library #21 
- [x] document changes in how calculations was done (affects 2011 library, see #25 ). — @katrinr

**Comment by orbeckst** [comment]
Online docs #1 would be nice. Maybe there's a quick way to make the README into a single-page readthedocs?

**Comment by philipwfowler** [comment]
Sorry storming for a grant. Will re-emerge in ~2 weeks. —Phil

**Comment by orbeckst** [comment]
Docs are online: https://www.mdanalysis.org/RotamerConvolveMD

**Comment by orbeckst** [comment]
@katrinr I think once #21 is done, we should make the 1.3.0 release.

I don't know how to make the conda packages but perhaps @kain88-de will be able to help. I started taking notes on how to make a release at https://github.com/MDAnalysis/RotamerConvolveMD/wiki

**Comment by orbeckst** [comment]
#25 is holding up a release.

**Comment by kain88-de** [comment]
Can we have a release? I currently cannot merge https://github.com/conda-forge/rotamerconvolvemd-feedstock/pull/1 because the released version does not work with current mdanalysis.

**Comment by kain88-de** [comment]
the blocker issue #25 is closed

**Comment by orbeckst** [comment]
Really busy today, and I am virtually away over the Thanksgiving days, so the earliest I am going to do anything is next week. If anyone else (@kain88-de @philipwfowler  @lukas-stelzl @katrinr ) wants to move forward please do – if you need access to pypi email me.

**Comment by kain88-de** [comment]
Enjoy Thanksgiving! 

It won't hurt if this takes another couple of days.

**Comment by orbeckst** [comment]
I pushed a 1.3.0 to pypi and updated the docs.

@kain88-de – does the conda feedstock https://github.com/MDAnalysis/rotamerconvolvemd-feedstock get automatically updated?

**Comment by kain88-de** [comment]
The feedstock should pick it up within a day.

**Comment by orbeckst** [comment]
Thanks, it did. I did a few edits and merged PR https://github.com/conda-forge/rotamerconvolvemd-feedstock/pull/3 – 1.3.0 should be up on conda-forge in a bit. Now that MDA works with Windows and Py3k I removed any such restrictions from our meta.yml... I think.
